// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcijC2DB-Qc7FEJ40VNgXmKwoWi-Yo62o',
    appId: '1:53200556775:web:f072e091ab728750fe0842',
    messagingSenderId: '53200556775',
    projectId: 'bla-bla-7',
    authDomain: 'bla-bla-7.firebaseapp.com',
    databaseURL: 'https://bla-bla-7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bla-bla-7.firebasestorage.app',
    measurementId: 'G-BXZ2BBEP03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz9wmxBRnEdjXJE_wDtqoYzkQky7MBXmA',
    appId: '1:53200556775:android:741ec785e0543856fe0842',
    messagingSenderId: '53200556775',
    projectId: 'bla-bla-7',
    databaseURL: 'https://bla-bla-7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bla-bla-7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyBgMSoxjckj9tQUU8kkxND2OLe-TTXsQ',
    appId: '1:53200556775:ios:e4030bdf2d3dd96efe0842',
    messagingSenderId: '53200556775',
    projectId: 'bla-bla-7',
    databaseURL: 'https://bla-bla-7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bla-bla-7.firebasestorage.app',
    iosBundleId: 'com.example.week3BlablaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyBgMSoxjckj9tQUU8kkxND2OLe-TTXsQ',
    appId: '1:53200556775:ios:e4030bdf2d3dd96efe0842',
    messagingSenderId: '53200556775',
    projectId: 'bla-bla-7',
    databaseURL: 'https://bla-bla-7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bla-bla-7.firebasestorage.app',
    iosBundleId: 'com.example.week3BlablaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcijC2DB-Qc7FEJ40VNgXmKwoWi-Yo62o',
    appId: '1:53200556775:web:14c3eb836a579537fe0842',
    messagingSenderId: '53200556775',
    projectId: 'bla-bla-7',
    authDomain: 'bla-bla-7.firebaseapp.com',
    databaseURL: 'https://bla-bla-7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bla-bla-7.firebasestorage.app',
    measurementId: 'G-X5Y9XZGBR1',
  );
}
